# Generated by Django 4.1.4 on 2022-12-12 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createtables', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseproject',
            name='name',
            field=models.CharField(default='client', max_length=255),
            preserve_default=False,
        ),
    ]
