# Generated by Django 4.1.4 on 2022-12-12 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createtables', '0002_databaseproject_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='databaseproject',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='databaseproject',
            name='id',
        ),
        migrations.AddField(
            model_name='databaseproject',
            name='auto_increment_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
